[package]
name = "plotmux"
version = "0.1.0"
edition = "2021"

path = "src/*"

[dependencies]
crossbeam-channel = "0.5.5"
sha1 = "0.10.0"
eframe = "0.18.0"

serde = { version = "1.0", features = ["derive"] }
bincode = "1.2.1"
image = "0.24.2"
