[package]
name = "hackathon"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

pyproc = { path = "../pyproc" }
ntpnet = { path = "../ntpnet" }

rscam = "0.5.5"
image = "0.24.2"
clap = { version = "4.0.7", features = ["derive"] }
fft2d = "0.1.0"
rustfft = "6.1.0"

libpulse-simple-binding = "2.25.0"
libpulse-sys = "1.19.3"
libpulse-binding = "2.26.0"

byteorder = "1.4.3"
tensorflow = "0.19.1"
itertools = "0.10.5"
